package org.cipango.media.api;

import java.util.List;

import org.mortbay.io.Buffer;

/**
 * Mixer is an audio multiplexer
 * 
 * It takes several inputs, mix them and provides one output. Mixer inputs and
 * the output will are all Buffers of the same size, using the same raw
 * format, i.e. mono-channel linear PCM 8000Hz signed 16 bits samples.
 * If one of the input is smaller than others, it will be processed up to its
 * end, and ignored after. If an audio stream is encoded, it has to be decoded
 * using its appropriate {@link Codec} class before it can be used by Mixer.
 * 
 * @author yohann
 */
public class Mixer implements Managed
{

    /**
     * Mix several Buffers into one Buffer. All inputs must use the same raw
     * format i.e. mono-channel linear PCM 8000Hz signed 16 bits samples. null
     * Buffers will be ignored, as well as empty buffers.
     * 
     * @param buffers the list of buffers to mix. All buffers should have the
     * same size
     * @return the unique Buffer generated by the mix of all inputs.
     */
    public Buffer mix(List<Buffer> buffers)
    {
        return null;
    }

}
