require 'rake/clean'
require 'fileutils'
require 'spec/rake/spectask'

Version = "1.0-SNAPSHOT"
JarName = "sipatra-#{Version}.jar"

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "sipatra"
    gem.summary = %Q{DSL for easy writting of SIP Servlet applications}
    gem.description = %Q{Sipatra is a Ruby DSL for easy writting of SIP Servlet applications}
    gem.email = ["dominique.broeglin@gmail.com", "jean-baptiste.morin@nexcom.fr"]
    gem.homepage = "http://blablabla"
    gem.authors = ["Dominique Broeglin", "Jean-Baptiste Morin"]
    gem.add_development_dependency "rspec", ">= 1.2.9"
    
    gem.files = FileList['lib/**/*.rb', 'lib/**/*/jar'].to_a
    
    # gem.add_development_dependency "yard", ">= 0"
    # gem is a Gem::Specification... see http://www.rubygems.org/read/chapter/20 for additional settings
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

require 'spec/rake/spectask'
Spec::Rake::SpecTask.new(:spec) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.spec_files = FileList['spec/**/*_spec.rb']
  spec.verbose = true
end

Spec::Rake::SpecTask.new(:rcov) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.pattern = 'spec/**/*_spec.rb'
  spec.rcov = true
end

task :spec => :check_dependencies

task :default => :spec

task :clean do
  rm_rf Dir["lib/sipatra", "lib/sipatra.rb"]
end

begin
  require 'yard'
  YARD::Rake::YardocTask.new
rescue LoadError
  task :yardoc do
    abort "YARD is not available. In order to run yardoc, you must: sudo gem install yard"
  end
end

file "lib/sipatra/#{JarName}" => "lib/sipatra" do
  system "maven package"
  cp "target/#{JarName}", "lib/sipatra"
end

directory "lib/sipatra" do
  mkdir_p "lib/sipatra"
end

file "lib/sipatra.rb" => "lib/sipatra" do
  cp_r FileList["src/main/resources/sipatra.rb", "src/main/resources/sipatra"], "lib/"
end
